global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dc-service'
    static_configs:
      - targets: ['marvelservice:8080']
      
  - job_name: 'marvel-service'
    static_configs:
      - targets: ['dcservice:8080']